# Generated by Django 5.2.7 on 2025-10-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(choices=[('EUR/PLN', 'EUR/PLN'), ('USD/PLN', 'USD/PLN'), ('CHF/PLN', 'CHF/PLN'), ('EUR/USD', 'EUR/USD'), ('EUR/CHF', 'EUR/CHF'), ('USD/CHF', 'USD/CHF')], max_length=7, unique=True)),
                ('buy_rate', models.FloatField()),
                ('sell_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
