# Generated by Django 5.2.7 on 2025-10-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypair',
            name='currency_pair',
            field=models.CharField(choices=[('EUR/PLN', 'EUR/PLN'), ('USD/PLN', 'USD/PLN'), ('CHF/PLN', 'CHF/PLN'), ('EUR/USD', 'EUR/USD'), ('EUR/CHF', 'EUR/CHF'), ('USD/CHF', 'USD/CHF'), ('PLN/EUR', 'PLN/EUR'), ('PLN/USD', 'PLN/USD'), ('PLN/CHF', 'PLN/CHF'), ('USD/EUR', 'USD/EUR'), ('CHF/EUR', 'CHF/EUR'), ('CHF/USD', 'CHF/USD')], max_length=7, unique=True),
        ),
    ]
