# Generated by Django 5.2.7 on 2025-10-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_currencypair_currency_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypair',
            name='currency_pair',
            field=models.CharField(choices=[('EUR/PLN', 'Eurpln'), ('USD/PLN', 'Usdpln'), ('CHF/PLN', 'Chfpln'), ('EUR/USD', 'Eurusd'), ('EUR/CHF', 'Eurchf'), ('USD/CHF', 'Usdchf'), ('PLN/EUR', 'Plneur'), ('PLN/USD', 'Plnusd'), ('PLN/CHF', 'Plnchf'), ('USD/EUR', 'Usdeur'), ('CHF/EUR', 'Chfeur'), ('CHF/USD', 'Chfusd')], max_length=7, unique=True),
        ),
    ]
